name: Bug
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behavior in the existing issues. If you can't find what you're looking for, then please open a new issue. 
        For questions about Publii functionality, **themes**, **plugins**, or other general queries, please contact our development team via the [community forum](https://forum.getpublii.com/).
        
        ---
        
        Thank you for taking the time to file a bug report. In order to help us investigate and fix the issue as quickly as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use to run Publii app? Please provide the version as well."
      placeholder: "macOS Monterey 12.2"
    validations:
      required: true  
  - type: input
    id: publii
    attributes:
      label: Publii version
      description: "Which Publii version do you use?"
      placeholder: "0.38.3 (build 14239)"
    validations:
      required: true
  - type: dropdown
    id: editor
    attributes:
      label: Post editor
      description: If you're reporting a bug with a post editor, please specify which one.
      options:
        - WYSIWYG editor
        - Block editor
        - Markdown editor
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output that can be generated with the Publii "Log Viewer" tool.
      render: shell
